### ISSUE TITLE
Please add 83,3 kbps speed

### ISSUE THREAD

**Issue by HeadonToast** [handmade0octopus/ESP32-TWAI-CAN#11]
Hello, is it possible to add 83,3 kbps as a choosable speed? This is used in some older cars and would be very useful.

**Comment by handmade0octopus** [comment]
I don't think ESP32 supports this speed unfortunately.

**Comment by handmade0octopus** [comment]
@HeadonToast this is super cool work, maybe we can implement some way of getting any speed this way?

Do you want to submit PR for this specific case or just leave it somewhere in the comments for others?

**Comment by HeadonToast** [comment]
I would just leave it here in the comments. The steps I did were just following the reference manual.

If you want any speed you have to more measurements and interpolate or fully understand the calculations. I do not need it nor I got the time for that. There are definitely calculators and libraries with calculators which could be adapted/improved since I have not found a working&easy to use library.
