### ISSUE TITLE
/storage/emulated/0/ArduinoDroid/userlibraries/ESP32-TWAI-CAN/src/ESP32-TWAI-CAN.hpp:24:25: fatal error: driver/twai.h: No such file or directory

### ISSUE THREAD

**Issue by Sorryuew** [handmade0octopus/ESP32-TWAI-CAN#13]

**Comment by handmade0octopus** [comment]
Looks like ide configuration error. Driver twai should be loaded from platform

**Comment by joshuavaneck** [comment]
I get the same error :(

**Comment by handmade0octopus** [comment]
What version of arduino for esp32 are you using?

Tbh never tested it on Arduino only.. always used platformio.
