### ISSUE TITLE
Adding  Basic example code for use with SN65HVD23x

### ISSUE THREAD

**Issue by MeY0u** [handmade0octopus/ESP32-TWAI-CAN#2]
Hey,
thank you for creating this repo of using CAN BUS, really came in handy.
At first it didnt quite work for me until i read again the datasheet of my chip "SN65HVD230" and released i am missing an enable pin.
Hence, i would like to suggest to add 2 example codes i wrote in a fork from this repo and include communication between 2 ESP's based on your code and SN65HVD230 RS Enable/Standby pin.

**Comment by handmade0octopus** [comment]
@MeY0u sorry for late reply - sure, create PR I will accept it.
