### ISSUE TITLE
Interrupts?

### ISSUE THREAD

**Issue by zejulio** [handmade0octopus/ESP32-TWAI-CAN#3]
Hello,

I've lost days with other library that worked on some ESP32 and not on others, I thought it was my fault or hardware, but your library works on all I've tested. 
Many thanks for this life savor!!

Is there a way to use interrupts or "callback" (.onReceive(processCanOnReceive) when a CAN message is received?

Thanks,

Julio Silva

**Comment by handmade0octopus** [comment]
@zejulio unfortunately not from what I can see. TWAI driver on ESP32 doesn't allow for callback.

You really need to create task for receive command, you can simply have:
```c++
if(ESP32Can.readFrame(rxFrame, portMAX_DELAY)) {
 // your callback
}
```

It will basically wait indefinitely for next message in queue not using resources.
