### ISSUE TITLE
Feedback: Works on original Arduino Nano ESP32

### ISSUE THREAD

**Issue by wltue** [handmade0octopus/ESP32-TWAI-CAN#5]
Works on original Arduino Nano ESP32 using Arduino drivers, changing pins works. (you need convert them from Arduino pins though).
Thank you for sharing.

**Comment by mitch-galea** [comment]
Hello, I was wondering what CAN transciever you used? I am trying to get it to work with the Adafruit CAN Pal and I'm not having luck? Also what pins were you using for RX and TX on the Arduino Nano ESP32 and how were these labelled in the code?
